package notify

func init() {
	RegisterSchemaEntryOrdered(50, SchemaEntry{
		"attachment_support": false,
		"category":           "native",
		"details": map[string]any{
			"args": map[string]any{
				"client_id": map[string]any{
					"map_to":   "client_id",
					"name":     "Client ID",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"cto": map[string]any{
					"default":  4,
					"map_to":   "cto",
					"name":     "Socket Connect Timeout",
					"private":  false,
					"required": false,
					"type":     "float",
				},
				"emojis": map[string]any{
					"default":  false,
					"map_to":   "emojis",
					"name":     "Interpret Emojis",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"format": map[string]any{
					"default":  "text",
					"map_to":   "format",
					"name":     "Notify Format",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"html", "markdown", "text"},
				},
				"overflow": map[string]any{
					"default":  "upstream",
					"map_to":   "overflow",
					"name":     "Overflow Mode",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"split", "truncate", "upstream"},
				},
				"qos": map[string]any{
					"default":  0,
					"map_to":   "qos",
					"max":      2,
					"min":      0,
					"name":     "QOS",
					"private":  false,
					"required": false,
					"type":     "int",
				},
				"retain": map[string]any{
					"default":  false,
					"map_to":   "retain",
					"name":     "Retain Messages",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"rto": map[string]any{
					"default":  4,
					"map_to":   "rto",
					"name":     "Socket Read Timeout",
					"private":  false,
					"required": false,
					"type":     "float",
				},
				"session": map[string]any{
					"default":  false,
					"map_to":   "session",
					"name":     "Use Session",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"store": map[string]any{
					"default":  true,
					"map_to":   "store",
					"name":     "Persistent Storage",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"to": map[string]any{
					"alias_of": "targets",
					"delim":    []string{",", " "},
				},
				"tz": map[string]any{
					"default":  nil,
					"map_to":   "tz",
					"name":     "Timezone",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"verify": map[string]any{
					"default":  true,
					"map_to":   "verify",
					"name":     "Verify SSL",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"version": map[string]any{
					"default":  "v3.1.1",
					"map_to":   "version",
					"name":     "Version",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"v3.1.1", "v3.1", "v5.0"},
				},
			},
			"kwargs":    map[string]any{},
			"templates": []string{"{schema}://{user}@{host}/{topic}", "{schema}://{user}@{host}:{port}/{topic}", "{schema}://{user}:{password}@{host}/{topic}", "{schema}://{user}:{password}@{host}:{port}/{topic}"},
			"tokens": map[string]any{
				"host": map[string]any{
					"map_to":   "host",
					"name":     "Hostname",
					"private":  false,
					"required": true,
					"type":     "string",
				},
				"password": map[string]any{
					"map_to":   "password",
					"name":     "Password",
					"private":  true,
					"required": true,
					"type":     "string",
				},
				"port": map[string]any{
					"map_to":   "port",
					"max":      65535,
					"min":      1,
					"name":     "Port",
					"private":  false,
					"required": false,
					"type":     "int",
				},
				"schema": map[string]any{
					"map_to":   "schema",
					"name":     "Schema",
					"private":  false,
					"required": true,
					"type":     "choice:string",
					"values":   []string{"mqtt", "mqtts"},
				},
				"targets": map[string]any{
					"delim":    []string{"/"},
					"group":    []string{"topic"},
					"map_to":   "targets",
					"name":     "Targets",
					"private":  false,
					"required": false,
					"type":     "list:string",
				},
				"topic": map[string]any{
					"map_to":   "targets",
					"name":     "Target Queue",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"user": map[string]any{
					"map_to":   "user",
					"name":     "User Name",
					"private":  false,
					"required": true,
					"type":     "string",
				},
			},
		},
		"enabled":   true,
		"protocols": []string{"mqtt"},
		"requirements": map[string]any{
			"details":              "",
			"packages_recommended": []any{},
			"packages_required":    []string{"paho-mqtt != 2.0.*"},
		},
		"secure_protocols": []string{"mqtts"},
		"service_name":     "MQTT Notification",
		"service_url":      nil,
		"setup_url":        "https://appriseit.com/services/mqtt/",
	})
}
