package notify

func init() {
	RegisterSchemaEntryOrdered(28, SchemaEntry{
		"attachment_support": false,
		"category":           "native",
		"details": map[string]any{
			"args": map[string]any{
				"cto": map[string]any{
					"default":  4,
					"map_to":   "cto",
					"name":     "Socket Connect Timeout",
					"private":  false,
					"required": false,
					"type":     "float",
				},
				"emojis": map[string]any{
					"default":  false,
					"map_to":   "emojis",
					"name":     "Interpret Emojis",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"format": map[string]any{
					"default":  "text",
					"map_to":   "format",
					"name":     "Notify Format",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"html", "markdown", "text"},
				},
				"image": map[string]any{
					"default":  true,
					"map_to":   "include_image",
					"name":     "Include Image",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"overflow": map[string]any{
					"default":  "upstream",
					"map_to":   "overflow",
					"name":     "Overflow Mode",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"split", "truncate", "upstream"},
				},
				"priority": map[string]any{
					"alias_of": "urgency",
				},
				"rto": map[string]any{
					"default":  4,
					"map_to":   "rto",
					"name":     "Socket Read Timeout",
					"private":  false,
					"required": false,
					"type":     "float",
				},
				"store": map[string]any{
					"default":  true,
					"map_to":   "store",
					"name":     "Persistent Storage",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"tz": map[string]any{
					"default":  nil,
					"map_to":   "tz",
					"name":     "Timezone",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"urgency": map[string]any{
					"default":  1,
					"map_to":   "urgency",
					"name":     "Urgency",
					"private":  false,
					"required": false,
					"type":     "choice:int",
					"values":   []any{0, 1, 2},
				},
				"verify": map[string]any{
					"default":  true,
					"map_to":   "verify",
					"name":     "Verify SSL",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"x": map[string]any{
					"map_to":   "x_axis",
					"min":      0,
					"name":     "X-Axis",
					"private":  false,
					"required": false,
					"type":     "int",
				},
				"y": map[string]any{
					"map_to":   "y_axis",
					"min":      0,
					"name":     "Y-Axis",
					"private":  false,
					"required": false,
					"type":     "int",
				},
			},
			"kwargs":    map[string]any{},
			"templates": []string{"{schema}://"},
			"tokens": map[string]any{
				"schema": map[string]any{
					"map_to":   "schema",
					"name":     "Schema",
					"private":  false,
					"required": true,
					"type":     "choice:string",
					"values":   []string{"dbus", "kde", "qt"},
				},
			},
		},
		"enabled":   false,
		"protocols": []string{"qt", "kde", "dbus"},
		"requirements": map[string]any{
			"details":              "libdbus-1.so.x must be installed.",
			"packages_recommended": []any{},
			"packages_required":    []any{},
		},
		"secure_protocols": nil,
		"service_name":     "DBus Notification",
		"service_url":      "http://www.freedesktop.org/Software/dbus/",
		"setup_url":        "https://appriseit.com/services/dbus/",
	})
}
