package notify

var chatSchemas = map[string]struct{}{
	"discord":  {},
	"feishu":   {},
	"gchat":    {},
	"guilded":  {},
	"lark":     {},
	"line":     {},
	"webex":    {},
	"wecombot": {},
	"wxteams":  {},
	"signal":   {},
	"signals":  {},
	"whatsapp": {},
	"ryver":    {},
	"zulip":    {},
	"rocket":   {},
	"rockets":  {},
	"slack":    {},
	"revolt":   {},
	"mmost":    {},
	"mmosts":   {},
	"dingtalk": {},
	"nctalk":   {},
	"nctalks":  {},
	"matrix":   {},
	"matrixs":  {},
	"threema":  {},
	"tgram":    {},
	"twist":    {},
	"tweet":    {},
	"twitter":  {},
	"x":        {},
}
