package notify

func init() {
	RegisterSchemaEntryOrdered(115, SchemaEntry{
		"service_name":       "Slack",
		"service_url":        "https://slack.com/",
		"setup_url":          "https://appriseit.com/services/slack/",
		"attachment_support": true,
		"category":           "native",
		"enabled":            true,
		"protocols":          []string(nil),
		"secure_protocols":   []string{"slack"},
		"requirements": map[string]any{
			"details":              "",
			"packages_recommended": []string{},
			"packages_required":    []string{},
		},
		"details": map[string]any{
			"args": map[string]any{
				"blocks": map[string]any{
					"default":  false,
					"map_to":   "use_blocks",
					"name":     "Use Blocks",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"cto": map[string]any{
					"default":  4.0,
					"map_to":   "cto",
					"name":     "Socket Connect Timeout",
					"private":  false,
					"required": false,
					"type":     "float",
				},
				"emojis": map[string]any{
					"default":  false,
					"map_to":   "emojis",
					"name":     "Interpret Emojis",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"footer": map[string]any{
					"default":  true,
					"map_to":   "include_footer",
					"name":     "Include Footer",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"format": map[string]any{
					"default":  "markdown",
					"map_to":   "format",
					"name":     "Notify Format",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"html", "markdown", "text"},
				},
				"image": map[string]any{
					"default":  true,
					"map_to":   "include_image",
					"name":     "Include Image",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"mode": map[string]any{
					"map_to":   "mode",
					"name":     "Message Mode",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"hook", "gov-hook", "bot"},
				},
				"overflow": map[string]any{
					"default":  "upstream",
					"map_to":   "overflow",
					"name":     "Overflow Mode",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"split", "truncate", "upstream"},
				},
				"rto": map[string]any{
					"default":  4.0,
					"map_to":   "rto",
					"name":     "Socket Read Timeout",
					"private":  false,
					"required": false,
					"type":     "float",
				},
				"store": map[string]any{
					"default":  true,
					"map_to":   "store",
					"name":     "Persistent Storage",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"timestamp": map[string]any{
					"default":  true,
					"map_to":   "include_timestamp",
					"name":     "Include Timestamp",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"to": map[string]any{
					"alias_of": "targets",
					"delim":    []string{",", " "},
				},
				"token": map[string]any{
					"alias_of": []string{"access_token", "token_a", "token_b", "token_c"},
					"name":     "Token",
				},
				"tz": map[string]any{
					"default":  nil,
					"map_to":   "tz",
					"name":     "Timezone",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"verify": map[string]any{
					"default":  true,
					"map_to":   "verify",
					"name":     "Verify SSL",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
			},
			"kwargs": map[string]any{},
			"templates": []string{
				"{schema}://{token_a}/{token_b}/{token_c}",
				"{schema}://{botname}@{token_a}/{token_b}{token_c}",
				"{schema}://{token_a}/{token_b}/{token_c}/{targets}",
				"{schema}://{botname}@{token_a}/{token_b}/{token_c}/{targets}",
				"{schema}://{access_token}/",
				"{schema}://{access_token}/{targets}",
			},
			"tokens": map[string]any{
				"access_token": map[string]any{
					"map_to":   "access_token",
					"name":     "OAuth Access Token",
					"private":  true,
					"regex":    []string{"^xox[abp]-[A-Z0-9-]+$", "i"},
					"required": true,
					"type":     "string",
				},
				"botname": map[string]any{
					"map_to":   "user",
					"name":     "Bot Name",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"schema": map[string]any{
					"default":  "slack",
					"map_to":   "schema",
					"name":     "Schema",
					"private":  false,
					"required": true,
					"type":     "choice:string",
					"values":   []string{"slack"},
				},
				"target_channels": map[string]any{
					"map_to":   "targets",
					"name":     "Target Channel",
					"prefix":   "#",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"target_email": map[string]any{
					"map_to":   "targets",
					"name":     "Target Email",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"target_encoded_id": map[string]any{
					"map_to":   "targets",
					"name":     "Target Encoded ID",
					"prefix":   "+",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"target_user": map[string]any{
					"map_to":   "targets",
					"name":     "Target User",
					"prefix":   "@",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"targets": map[string]any{
					"delim":    []string{"/"},
					"group":    []string{"target_channels", "target_email", "target_encoded_id", "target_user"},
					"map_to":   "targets",
					"name":     "Targets",
					"private":  false,
					"required": false,
					"type":     "list:string",
				},
				"token_a": map[string]any{
					"map_to":   "token_a",
					"name":     "Token A",
					"private":  true,
					"regex":    []string{"^[A-Z0-9]+$", "i"},
					"required": false,
					"type":     "string",
				},
				"token_b": map[string]any{
					"map_to":   "token_b",
					"name":     "Token B",
					"private":  true,
					"regex":    []string{"^[A-Z0-9]+$", "i"},
					"required": false,
					"type":     "string",
				},
				"token_c": map[string]any{
					"map_to":   "token_c",
					"name":     "Token C",
					"private":  true,
					"regex":    []string{"^[A-Za-z0-9]+$", "i"},
					"required": false,
					"type":     "string",
				},
			},
		},
	})
}
