package notify

func init() {
	RegisterSchemaEntryOrdered(13, SchemaEntry{
		"service_name":       "ntfy",
		"service_url":        "https://ntfy.sh/",
		"setup_url":          "https://appriseit.com/services/ntfy/",
		"attachment_support": true,
		"category":           "native",
		"enabled":            true,
		"protocols":          []string{"ntfy"},
		"secure_protocols":   []string{"ntfys"},
		"requirements": map[string]any{
			"details":              "",
			"packages_recommended": []string{},
			"packages_required":    []string{},
		},
		"details": map[string]any{
			"args": map[string]any{
				"actions": map[string]any{
					"map_to":   "actions",
					"name":     "Actions",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"attach": map[string]any{
					"map_to":   "attach",
					"name":     "Attach",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"auth": map[string]any{
					"default":  "basic",
					"map_to":   "auth",
					"name":     "Authentication Type",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"basic", "token"},
				},
				"avatar_url": map[string]any{
					"map_to":   "avatar_url",
					"name":     "Avatar URL",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"click": map[string]any{
					"map_to":   "click",
					"name":     "Click",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"cto": map[string]any{
					"default":  4.0,
					"map_to":   "cto",
					"name":     "Socket Connect Timeout",
					"private":  false,
					"required": false,
					"type":     "float",
				},
				"delay": map[string]any{
					"map_to":   "delay",
					"name":     "Delay",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"email": map[string]any{
					"map_to":   "email",
					"name":     "Email",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"emojis": map[string]any{
					"default":  false,
					"map_to":   "emojis",
					"name":     "Interpret Emojis",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"filename": map[string]any{
					"map_to":   "filename",
					"name":     "Attach Filename",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"format": map[string]any{
					"default":  "text",
					"map_to":   "format",
					"name":     "Notify Format",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"html", "markdown", "text"},
				},
				"image": map[string]any{
					"default":  true,
					"map_to":   "include_image",
					"name":     "Include Image",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"mode": map[string]any{
					"default":  "private",
					"map_to":   "mode",
					"name":     "Mode",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"cloud", "private"},
				},
				"overflow": map[string]any{
					"default":  "upstream",
					"map_to":   "overflow",
					"name":     "Overflow Mode",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"split", "truncate", "upstream"},
				},
				"priority": map[string]any{
					"default":  "default",
					"map_to":   "priority",
					"name":     "Priority",
					"private":  false,
					"required": false,
					"type":     "choice:string",
					"values":   []string{"max", "high", "default", "low", "min"},
				},
				"rto": map[string]any{
					"default":  4.0,
					"map_to":   "rto",
					"name":     "Socket Read Timeout",
					"private":  false,
					"required": false,
					"type":     "float",
				},
				"store": map[string]any{
					"default":  true,
					"map_to":   "store",
					"name":     "Persistent Storage",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
				"tags": map[string]any{
					"map_to":   "tags",
					"name":     "Tags",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"to": map[string]any{
					"alias_of": "targets",
					"delim":    []string{",", " "},
				},
				"token": map[string]any{
					"alias_of": "token",
				},
				"tz": map[string]any{
					"default":  nil,
					"map_to":   "tz",
					"name":     "Timezone",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"verify": map[string]any{
					"default":  true,
					"map_to":   "verify",
					"name":     "Verify SSL",
					"private":  false,
					"required": false,
					"type":     "bool",
				},
			},
			"kwargs": map[string]any{},
			"templates": []string{
				"{schema}://{topic}",
				"{schema}://{host}/{targets}",
				"{schema}://{host}:{port}/{targets}",
				"{schema}://{user}@{host}/{targets}",
				"{schema}://{user}@{host}:{port}/{targets}",
				"{schema}://{user}:{password}@{host}/{targets}",
				"{schema}://{user}:{password}@{host}:{port}/{targets}",
				"{schema}://{token}@{host}/{targets}",
				"{schema}://{token}@{host}:{port}/{targets}",
			},
			"tokens": map[string]any{
				"host": map[string]any{
					"map_to":   "host",
					"name":     "Hostname",
					"private":  false,
					"required": false,
					"type":     "string",
				},
				"password": map[string]any{
					"map_to":   "password",
					"name":     "Password",
					"private":  true,
					"required": false,
					"type":     "string",
				},
				"port": map[string]any{
					"map_to":   "port",
					"max":      65535,
					"min":      1,
					"name":     "Port",
					"private":  false,
					"required": false,
					"type":     "int",
				},
				"schema": map[string]any{
					"map_to":   "schema",
					"name":     "Schema",
					"private":  false,
					"required": true,
					"type":     "choice:string",
					"values":   []string{"ntfy", "ntfys"},
				},
				"targets": map[string]any{
					"delim":    []string{"/"},
					"group":    []string{"topic"},
					"map_to":   "targets",
					"name":     "Targets",
					"private":  false,
					"required": false,
					"type":     "list:string",
				},
				"token": map[string]any{
					"map_to":   "token",
					"name":     "Token",
					"private":  true,
					"required": false,
					"type":     "string",
				},
				"topic": map[string]any{
					"map_to":   "targets",
					"name":     "Topic",
					"private":  false,
					"regex":    []string{"^[a-z0-9_-]{1,64}$", "i"},
					"required": false,
					"type":     "string",
				},
				"user": map[string]any{
					"map_to":   "user",
					"name":     "Username",
					"private":  false,
					"required": false,
					"type":     "string",
				},
			},
		},
	})
}
