[package]
name = "apprise-go"
changelog = "CHANGELOG.md"
versioned_files = [
  { path = "internal/version/version.go", regex = "var\\s+Version\\s*=\\s*\\\"(?<version>[^\\\"]+)\\\"" }
]

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git checkout -B knope/release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\""

[[workflows.steps]]
type = "Command"
command = "git push --force-with-lease origin knope/release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[bot.releases]
enabled = true

[github]
owner = "unraid"
repo = "apprise-go"
